# Generated by Django 4.2.4 on 2023-08-10 18:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('thread', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='likes',
            field=models.ManyToManyField(related_name='liked_threads', through='thread.Like', to=settings.AUTH_USER_MODEL),
        ),
    ]
