# Generated by Django 4.2.4 on 2023-08-11 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thread', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='username',
            new_name='user',
        ),
    ]
