# Generated by Django 4.2.4 on 2023-08-15 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thread', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='quoted_content',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='quoted_image',
        ),
    ]
