# Generated by Django 4.2.4 on 2023-08-15 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thread', '0003_remove_thread_quoted_content_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thread',
            old_name='reposted_thread',
            new_name='quoted_thread',
        ),
        migrations.AddField(
            model_name='thread',
            name='quoted_content',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='thread',
            name='quoted_image',
            field=models.ImageField(blank=True, null=True, upload_to='quoted_thread_pictures/'),
        ),
    ]
