# Generated by Django 4.2.4 on 2023-08-11 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thread', '0003_rename_username_comment_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='username',
        ),
    ]
