# Generated by Django 4.2.4 on 2023-08-11 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thread', '0005_comment_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='username',
            new_name='user',
        ),
    ]
