# Generated by Django 4.2.4 on 2023-10-10 16:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('thread', '0006_alter_comment_content_alter_thread_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='thread_picture',
        ),
        migrations.AddField(
            model_name='comment',
            name='mentions',
            field=models.ManyToManyField(blank=True, related_name='mentioned_in_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='thread',
            name='mentioned_users',
            field=models.ManyToManyField(blank=True, related_name='mentioned_in_threads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='thread',
            name='thread_media',
            field=models.FileField(blank=True, null=True, upload_to='thread_media/'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='content',
            field=models.TextField(blank=True, default='', max_length=280),
        ),
    ]
