# Generated by Django 4.2.4 on 2023-08-11 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thread', '0007_comment_likes_commentlike'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='likes',
        ),
    ]
