# Generated by Django 4.2.4 on 2023-08-04 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_website_customuser_link_customuser_is_private'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='location',
        ),
    ]
