<<<<<<< HEAD
# Generated by Django 4.2.4 on 2023-08-09 15:25
=======
# Generated by Django 4.2.4 on 2023-08-09 16:38
>>>>>>> natalia

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_otp_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
<<<<<<< HEAD
            field=models.CharField(db_index=True, max_length=50, unique=True),
=======
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
>>>>>>> natalia
        ),
    ]
