# Generated by Django 4.2.4 on 2023-08-15 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_followingsystem_customuser_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='followingsystem',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='followingsystem',
            name='request_sent',
            field=models.BooleanField(default=False),
        ),
    ]
