# Generated by Django 4.2.4 on 2023-08-23 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_subscriptionrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='followingsystem',
            name='request_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.DeleteModel(
            name='SubscriptionRequest',
        ),
    ]
