# Generated by Django 4.2.4 on 2023-08-23 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_followingsystem_request_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followingsystem',
            name='request_status',
        ),
        migrations.AddField(
            model_name='followingsystem',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
