# Generated by Django 4.2.4 on 2023-10-10 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_customuser_auth_provider_customuser_is_verified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='follower_requests',
        ),
        migrations.DeleteModel(
            name='FollowerRequest',
        ),
    ]
