# Generated by Django 4.2.4 on 2023-10-10 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_remove_customuser_follower_requests_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='followingsystem',
            name='is_pending',
            field=models.BooleanField(default=True),
        ),
    ]
